{"version":3,"sources":["add/iterable-operators/catcherror.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,SAAS,EAAE,MAAM,0BAA0B,CAAC;AACrD,OAAO,EAAE,UAAU,EAAE,MAAM,qCAAqC,CAAC;AAEjE;;GAEG;AACH,MAAM,UAAU,eAAe,CAE7B,EAA+B;IAE/B,OAAO,UAAU,CAAO,EAAE,CAAC,CAAC,IAAI,CAAC,CAAC;AACpC,CAAC;AAED,SAAS,CAAC,SAAS,CAAC,UAAU,GAAG,eAAe,CAAC","file":"catcherror.js","sourcesContent":["import { IterableX } from '../../iterable/iterablex';\nimport { catchError } from '../../iterable/operators/catcherror';\n\n/**\n * @ignore\n */\nexport function catchErrorProto<T, R>(\n  this: IterableX<T>,\n  fn: (error: any) => Iterable<R>\n): IterableX<T | R> {\n  return catchError<T, R>(fn)(this);\n}\n\nIterableX.prototype.catchError = catchErrorProto;\n\ndeclare module '../../iterable/iterablex' {\n  interface IterableX<T> {\n    catchError: typeof catchErrorProto;\n  }\n}\n"]}